with Ada.Characters.Handling;
with Ada.Containers.Indefinite_Ordered_Maps;
with Ada.Directories;
with Ada.Strings.Fixed;
with Ada.Text_IO;

with Codegen.Config;
with Codegen.Names;
with Codegen.RTGen_Model;

package body Codegen.Emit_High is

   use C_Model;

   NL : constant Character := ASCII.LF;

   Banner : constant String :=
     "--  GENERATED by tools/opendaq_codegen - DO NOT EDIT."
     & NL
     & "--  Regenerate with: ./daq gen"
     & NL;

   --  Interfaces implemented by hand in the Daq core (or deliberately not
   --  wrapped). Their handles map to hand types in profiles.
   function Is_Hand_Interface (Name : String) return Boolean is
     (Name = "BaseObject" or else Name = "String" or else Name = "List"
      or else Name = "Dict" or else Name = "Event"
      or else Name = "EventHandler" or else Name = "Function"
      or else Name = "Procedure" or else Name = "Iterator"
      or else Name = "Iterable" or else Name = "Boolean"
      or else Name = "Integer" or else Name = "Float"
      or else Name = "Number" or else Name = "CoreType");

   --  Methods excluded from generation (semantics the mechanical mapping
   --  would get wrong; reachable via the low-level bindings instead).
   function Is_Excluded_Method (C_Name : String) return Boolean is
     (C_Name = "daqStreamReader_skipSamples");

   --  NonInterfaceName -> Ada type name.
   function Type_Name (Non_Iface : String) return String is
   begin
      if Non_Iface = "Range" then
         return "Value_Range";
      elsif Non_Iface = "Type" then
         return "Type_Info";
      else
         return Names.To_Ada_Case (Non_Iface);
      end if;
   end Type_Name;

   procedure Run
     (DB   : C_Model.Database;
      Opts : Options;
      W    : in out Output.Writer)
   is
      use Ada.Text_IO;

      package Name_Maps is new
        Ada.Containers.Indefinite_Ordered_Maps (String, String);

      Model      : RTGen_Model.Interface_Vectors.Vector;
      Base_Of    : Name_Maps.Map;   --  NonIface -> base NonIface
      Gen_Set    : String_Sets.Set; --  NonIface names we generate
      Type_Names : String_Sets.Set; --  Ada type names (collision guard)
      Symbols    : String_Sets.Set; --  exported symbols (may be empty)
      Skipped    : String_Vectors.Vector;

      --  C proc name -> index in DB.Procs (for profile lookup)
      package Proc_Maps is new
        Ada.Containers.Indefinite_Ordered_Maps (String, Positive);
      Proc_Index : Proc_Maps.Map;

      Intf_Id_Set : String_Sets.Set;  --  DAQ_*_INTF_ID data-import names

      function Have_Symbol (C_Name : String) return Boolean is
        (Symbols.Is_Empty or else Symbols.Contains (C_Name));

      --  Ada expression producing a correctly-typed interface pointer for a
      --  Daq.Object'Class actual whose C parameter is a SPECIFIC interface
      --  (daqNumber*, daqFunction*, ...). Pointer identity only holds along
      --  the single-inheritance chain, so these must go through
      --  borrowInterface (Daq.Borrow_For). "" when neither the
      --  getInterfaceId function nor the id data import exists.
      function Obj_Borrow_Expr
        (C_Type : String; Actual : String) return String
      is
         Getter : constant String := C_Type & "_getInterfaceId";
      begin
         if Proc_Index.Contains (Getter) and then Have_Symbol (Getter) then
            declare
               Pkg : constant String :=
                 Config.Package_For_Group
                   (-DB.Procs (Proc_Index.Element (Getter)).Group);
            begin
               return "Copendaq.Types." & C_Type & " (Borrow_For ("
                 & Actual & "," & NL & "            Copendaq." & Pkg & "."
                 & Getter & "'Access, """ & C_Type & """))";
            end;
         end if;
         --  daq<Name> -> DAQ_<UPPER_SNAKE>_INTF_ID
         declare
            Bare : constant String :=
              C_Type (C_Type'First + 3 .. C_Type'Last);
            Const : constant String :=
              "DAQ_"
              & Ada.Characters.Handling.To_Upper
                  (Names.To_Ada_Case (Bare))
              & "_INTF_ID";
         begin
            if Intf_Id_Set.Contains (Const)
              and then Have_Symbol (Const)
            then
               return "Copendaq.Types." & C_Type & " (Borrow_For ("
                 & Actual & "," & NL & "            Copendaq.Intf_IDs."
                 & Const & ", """ & C_Type & """))";
            end if;
         end;
         return "";
      end Obj_Borrow_Expr;

      procedure Load_Symbols is
         F : Ada.Text_IO.File_Type;
      begin
         if not Ada.Directories.Exists (-Opts.Symbols) then
            Put_Line ("emit_high: WARNING no symbols file; "
                      & "skipping export reconciliation");
            return;
         end if;
         Open (F, In_File, -Opts.Symbols);
         while not End_Of_File (F) loop
            declare
               Line : constant String := Get_Line (F);
            begin
               if Line'Length > 0 then
                  Symbols.Include (Line);
               end if;
            end;
         end loop;
         Close (F);
      end Load_Symbols;

      ----------------------------------------------------------------
      --  Parameter mapping
      ----------------------------------------------------------------

      --  How a C parameter surfaces in the high-level profile.
      type Param_Class is
        (PC_Self,        --  first param: own handle
         PC_In_Bool,     --  daqBool          -> Boolean
         PC_In_Int,      --  daqInt           -> Long_Long_Integer
         PC_In_UInt,     --  daqUInt          -> Copendaq.daqUInt
         PC_In_Float,    --  daqFloat         -> Long_Float
         PC_In_Size,     --  daqSizeT         -> Natural
         PC_In_Enum,     --  enum             -> the Copendaq enum type
         PC_In_Str,      --  daqConstCharPtr  -> String (New_String/Free)
         PC_In_DaqStr,   --  daqString*       -> String (temp daqString)
         PC_In_List,     --  daqList*         -> Daq.Lists.List'Class
         PC_In_Dict,     --  daqDict*         -> Daq.Dicts.Dict'Class
         PC_In_Event,    --  daqEvent*        -> Daq.Events.Event'Class
         PC_In_Obj,      --  daqBaseObject* / hand ifaces -> Daq.Object'Class
         PC_In_Iface,    --  generated iface  -> <T>'Class
         PC_In_Err,      --  daqErrCode       -> Copendaq.daqErrCode
         PC_Out_Bool, PC_Out_Int, PC_Out_UInt, PC_Out_Float, PC_Out_Size,
         PC_Out_Enum,    --  enum out
         PC_Out_CStr,    --  daqCharPtr out   -> String (borrowed)
         PC_Out_DaqStr,  --  daqString**      -> String (owned, released)
         PC_Out_List, PC_Out_Dict, PC_Out_Event,
         PC_Out_Obj,     --  daqBaseObject**  -> Daq.Object
         PC_Out_Iface,   --  generated iface out
         PC_Unmappable);

      subtype Out_Class is Param_Class range PC_Out_Bool .. PC_Out_Iface;
      subtype In_Class is Param_Class range PC_In_Bool .. PC_In_Err;

      type Param_Info is record
         Class    : Param_Class := PC_Unmappable;
         Ada_Name : Unbounded_String;
         C_Type   : Unbounded_String;  --  base C type (e.g. daqSignal)
         Iface    : Unbounded_String;  --  NonIface name for PC_*_Iface
      end record;

      function Classify (P : Param; Position : Positive) return Param_Info is
         T    : constant String := -P.C_Type;
         Info : Param_Info;

         function Iface_Of_Handle return String is
            --  daqSignal -> Signal (when generated); "" otherwise
         begin
            if T'Length > 3 and then T (T'First .. T'First + 2) = "daq" then
               declare
                  N : constant String := T (T'First + 3 .. T'Last);
               begin
                  if Gen_Set.Contains (N) then
                     return N;
                  end if;
               end;
            end if;
            return "";
         end Iface_Of_Handle;

      begin
         Info.Ada_Name := +Names.To_Ada_Case (-P.Name);
         --  A formal named like a generated type would hide that type for
         --  the rest of the profile ("Signal : Signal'Class" is illegal).
         if Type_Names.Contains
           (Ada.Characters.Handling.To_Lower (-Info.Ada_Name))
         then
            Info.Ada_Name := +("The_" & (-Info.Ada_Name));
         end if;
         Info.C_Type := P.C_Type;

         if T = "daqBool" then
            Info.Class := (if P.Ptr = 0 then PC_In_Bool
                           elsif P.Ptr = 1 then PC_Out_Bool
                           else PC_Unmappable);
         elsif T = "daqInt" then
            Info.Class := (if P.Ptr = 0 then PC_In_Int
                           elsif P.Ptr = 1 then PC_Out_Int
                           else PC_Unmappable);
         elsif T = "daqUInt" or else T = "daqEnumType" then
            Info.Class := (if P.Ptr = 0 then PC_In_UInt
                           elsif P.Ptr = 1 then PC_Out_UInt
                           else PC_Unmappable);
         elsif T = "daqFloat" then
            Info.Class := (if P.Ptr = 0 then PC_In_Float
                           elsif P.Ptr = 1 then PC_Out_Float
                           else PC_Unmappable);
         elsif T = "daqSizeT" then
            Info.Class := (if P.Ptr = 0 then PC_In_Size
                           elsif P.Ptr = 1 then PC_Out_Size
                           else PC_Unmappable);
         elsif T = "daqErrCode" then
            Info.Class := (if P.Ptr = 0 then PC_In_Err else PC_Unmappable);
         elsif T = "daqCoreType" or else T = "daqLockingStrategy"
           or else DB.Known_Enums.Contains (T)
         then
            Info.Class := (if P.Ptr = 0 then PC_In_Enum
                           elsif P.Ptr = 1 then PC_Out_Enum
                           else PC_Unmappable);
         elsif T = "daqConstCharPtr" or else T = "daqCharPtr" then
            Info.Class := (if P.Ptr = 0 then PC_In_Str
                           elsif P.Ptr = 1 then PC_Out_CStr
                           else PC_Unmappable);
         elsif T = "daqString" then
            Info.Class := (if P.Ptr = 1 then PC_In_DaqStr
                           elsif P.Ptr = 2 then PC_Out_DaqStr
                           else PC_Unmappable);
         elsif T = "daqList" then
            Info.Class := (if P.Ptr = 1 then PC_In_List
                           elsif P.Ptr = 2 then PC_Out_List
                           else PC_Unmappable);
         elsif T = "daqDict" then
            Info.Class := (if P.Ptr = 1 then PC_In_Dict
                           elsif P.Ptr = 2 then PC_Out_Dict
                           else PC_Unmappable);
         elsif T = "daqEvent" then
            Info.Class := (if P.Ptr = 1 then PC_In_Event
                           elsif P.Ptr = 2 then PC_Out_Event
                           else PC_Unmappable);
         elsif T = "daqBaseObject" then
            Info.Class := (if P.Ptr = 1 then PC_In_Obj
                           elsif P.Ptr = 2 then PC_Out_Obj
                           else PC_Unmappable);
         elsif DB.Known_Opaque.Contains (T) then
            declare
               N : constant String := Iface_Of_Handle;
            begin
               if N /= "" then
                  Info.Iface := +N;
                  Info.Class := (if P.Ptr = 1 then PC_In_Iface
                                 elsif P.Ptr = 2 then PC_Out_Iface
                                 else PC_Unmappable);
               else
                  --  Hand interface or unmodeled: generic object
                  Info.Class := (if P.Ptr = 1 then PC_In_Obj
                                 elsif P.Ptr = 2 then PC_Out_Obj
                                 else PC_Unmappable);
               end if;
            end;
         else
            Info.Class := PC_Unmappable;
         end if;

         if Position = 1
           and then P.Ptr = 1
           and then (DB.Known_Opaque.Contains (T))
         then
            Info.Class := PC_Self;
         end if;
         return Info;
      end Classify;

      function Ada_In_Type (I : Param_Info) return String is
      begin
         case I.Class is
            when PC_In_Bool   => return "Boolean";
            when PC_In_Int    => return "Long_Long_Integer";
            when PC_In_UInt   =>
               return (if -I.C_Type = "daqEnumType"
                       then "Copendaq.daqEnumType" else "Copendaq.daqUInt");
            when PC_In_Float  => return "Long_Float";
            when PC_In_Size   => return "Natural";
            when PC_In_Err    => return "Copendaq.daqErrCode";
            when PC_In_Enum   =>
               declare
                  T : constant String := -I.C_Type;
               begin
                  if T = "daqCoreType" or else T = "daqLockingStrategy" then
                     return "Copendaq." & T;
                  end if;
                  return "Copendaq.Types." & T;
               end;
            when PC_In_Str | PC_In_DaqStr => return "String";
            when PC_In_List   => return "Daq.Lists.List'Class";
            when PC_In_Dict   => return "Daq.Dicts.Dict'Class";
            when PC_In_Event  => return "Daq.Events.Event'Class";
            when PC_In_Obj    => return "Daq.Object'Class";
            when PC_In_Iface  => return Type_Name (-I.Iface) & "'Class";
            when others       => return "";
         end case;
      end Ada_In_Type;

      --  As_Result: interface results are class-wide ('Class) so the
      --  function is NOT a primitive of the (possibly already frozen)
      --  result type, and inherited-constructor ambiguities cannot arise.
      --  Non-result interface outs surface as plain Daq.Object (specific
      --  types from other packages are never primitives here); cast as
      --  needed with As_X.
      function Ada_Out_Type
        (I : Param_Info; As_Result : Boolean) return String is
      begin
         case I.Class is
            when PC_Out_Bool   => return "Boolean";
            when PC_Out_Int    => return "Long_Long_Integer";
            when PC_Out_UInt   =>
               return (if -I.C_Type = "daqEnumType"
                       then "Copendaq.daqEnumType" else "Copendaq.daqUInt");
            when PC_Out_Float  => return "Long_Float";
            when PC_Out_Size   => return "Natural";
            when PC_Out_Enum   =>
               declare
                  T : constant String := -I.C_Type;
               begin
                  if T = "daqCoreType" or else T = "daqLockingStrategy" then
                     return "Copendaq." & T;
                  end if;
                  return "Copendaq.Types." & T;
               end;
            when PC_Out_CStr | PC_Out_DaqStr => return "String";
            when PC_Out_List   => return "Daq.Lists.List";
            when PC_Out_Dict   => return "Daq.Dicts.Dict";
            when PC_Out_Event  => return "Daq.Events.Event";
            when PC_Out_Obj    => return "Daq.Object";
            when PC_Out_Iface  =>
               return (if As_Result
                       then Type_Name (-I.Iface) & "'Class"
                       else "Daq.Object");
            when others        => return "";
         end case;
      end Ada_Out_Type;

      ----------------------------------------------------------------
      --  Per-method emission
      ----------------------------------------------------------------

      Spec_B : Unbounded_String;
      Body_B : Unbounded_String;

      --  One method/factory. Iface = "" for factories emitted standalone.
      procedure Emit_Subprogram
        (P          : Proc_Decl;
         Self_Iface : String;   --  NonIface of Self ("" for factory)
         Ada_Name   : String)
      is
         C_Name  : constant String := -P.Name;
         Pkg     : constant String :=
           Config.Package_For_Group (-P.Group);
         Infos   : array (1 .. Natural (P.Params.Length)) of Param_Info;
         N_Out   : Natural := 0;
         Last_Out : Natural := 0;
         Factory : constant Boolean := Self_Iface = "";
         Broken  : Boolean := False;
         Ret_Str : constant String := -P.Ret;
      begin
         if Is_Excluded_Method (C_Name) then
            Skipped.Append (C_Name & " (excluded by config)");
            return;
         end if;
         if not Have_Symbol (C_Name) then
            Skipped.Append (C_Name & " (not exported by libcopendaq)");
            return;
         end if;
         if Ret_Str /= "daqErrCode" then
            Skipped.Append (C_Name & " (non-ErrCode return)");
            return;
         end if;

         for I in Infos'Range loop
            Infos (I) := Classify (P.Params (I), I);
            if Infos (I).Class = PC_Unmappable then
               Broken := True;
            elsif Infos (I).Class = PC_In_Obj
              and then -Infos (I).C_Type /= "daqBaseObject"
              and then Obj_Borrow_Expr (-Infos (I).C_Type, "X") = ""
            then
               Broken := True;  --  no way to obtain the interface pointer
            elsif Infos (I).Class in Out_Class then
               N_Out := N_Out + 1;
               Last_Out := I;
            end if;
         end loop;

         if Factory then
            --  first param must be the created object (out)
            if Infos'Length = 0
              or else Infos (1).Class not in
                        PC_Out_Iface | PC_Out_Obj | PC_Out_List | PC_Out_Dict
            then
               Skipped.Append (C_Name & " (factory shape not recognized)");
               return;
            end if;
         else
            if Infos'Length = 0 or else Infos (1).Class /= PC_Self then
               Skipped.Append (C_Name & " (no self parameter)");
               return;
            end if;
         end if;

         if Broken then
            Skipped.Append (C_Name & " (unmappable parameter)");
            return;
         end if;

         --  Shape: function whenever there is exactly one out param (the C
         --  API often puts it before trailing in-params, e.g. getSignals'
         --  search filter).
         declare
            As_Function : constant Boolean := N_Out = 1;
            Result_Idx : constant Natural :=
              (if As_Function then Last_Out else 0);

            Prof   : Unbounded_String;
            First  : Boolean := True;

            procedure Add_Formal (Text : String) is
            begin
               if First then
                  Append (Prof, NL & "     (");
               else
                  Append (Prof, ";" & NL & "      ");
               end if;
               Append (Prof, Text);
               First := False;
            end Add_Formal;

         begin
            for I in Infos'Range loop
               declare
                  Inf : Param_Info renames Infos (I);
                  Nm  : constant String := -Inf.Ada_Name;
               begin
                  if Inf.Class = PC_Self then
                     Add_Formal
                       ("Self : " & Type_Name (Self_Iface) & "'Class");
                  elsif Inf.Class in In_Class then
                     Add_Formal (Nm & " : " & Ada_In_Type (Inf));
                  elsif Inf.Class in Out_Class
                    and then I /= Result_Idx
                  then
                     Add_Formal
                       (Nm & " : out " & Ada_Out_Type (Inf, False));
                  end if;
               end;
            end loop;
            if not First then
               Append (Prof, ")");
            end if;

            declare
               Head : constant String :=
                 (if Result_Idx /= 0
                  then "function " & Ada_Name & (-Prof)
                       & " return "
                       & Ada_Out_Type (Infos (Result_Idx), True)
                  else "procedure " & Ada_Name & (-Prof));
            begin
               Append (Spec_B, "   " & Head & ";" & NL);
               Append (Body_B, "   " & Head & NL & "   is" & NL);
            end;

            --  Locals: one per non-self parameter (C-side view), plus Code.
            for I in Infos'Range loop
               declare
                  Inf : Param_Info renames Infos (I);
                  Nm  : constant String := "L" & Ada.Strings.Fixed.Trim
                          (I'Image, Ada.Strings.Both);
                  CT  : constant String := -Inf.C_Type;

                  function C_View return String is
                    (if DB.Known_Opaque.Contains (CT)
                       and then CT /= "daqBaseObject"
                     then "Copendaq.Types." & CT
                     elsif CT = "daqCoreType" or else CT = "daqLockingStrategy"
                       or else CT = "daqBaseObject"
                     then "Copendaq." & CT
                     elsif DB.Known_Enums.Contains (CT)
                     then "Copendaq.Types." & CT
                     else "Copendaq." & CT);
               begin
                  case Inf.Class is
                     when PC_Self => null;
                     when PC_In_Str =>
                        Append (Body_B,
                          "      " & Nm
                          & " : Interfaces.C.Strings.chars_ptr :="
                          & NL & "        Interfaces.C.Strings.New_String ("
                          & (-Inf.Ada_Name) & ");" & NL);
                     when PC_In_DaqStr =>
                        Append (Body_B,
                          "      " & Nm
                          & " : Copendaq.daqBaseObject :="
                          & " New_String_Handle (" & (-Inf.Ada_Name) & ");"
                          & NL);
                     when PC_Out_Bool =>
                        Append (Body_B, "      " & Nm
                                & " : Copendaq.daqBool := 0;" & NL);
                     when PC_Out_Int =>
                        Append (Body_B, "      " & Nm
                                & " : Copendaq.daqInt := 0;" & NL);
                     when PC_Out_UInt =>
                        Append (Body_B, "      " & Nm & " : " & C_View
                                & " := 0;" & NL);
                     when PC_Out_Float =>
                        Append (Body_B, "      " & Nm
                                & " : Copendaq.daqFloat := 0.0;" & NL);
                     when PC_Out_Size =>
                        Append (Body_B, "      " & Nm
                                & " : Copendaq.daqSizeT := 0;" & NL);
                     when PC_Out_Enum =>
                        Append (Body_B, "      " & Nm & " : " & C_View & ";"
                                & NL);
                     when PC_Out_CStr =>
                        Append (Body_B,
                          "      " & Nm
                          & " : Copendaq.daqCharPtr :="
                          & " Interfaces.C.Strings.Null_Ptr;" & NL);
                     when PC_Out_DaqStr | PC_Out_List | PC_Out_Dict
                        | PC_Out_Event | PC_Out_Obj | PC_Out_Iface =>
                        Append (Body_B, "      " & Nm & " : " & C_View & ";"
                                & NL);
                     when others => null;
                  end case;
               end;
            end loop;
            Append (Body_B, "      Code : Copendaq.daqErrCode;" & NL);
            Append (Body_B, "   begin" & NL);

            --  The C call.
            Append (Body_B, "      Code := Copendaq." & Pkg & "."
                    & C_Name & NL & "        (");
            for I in Infos'Range loop
               declare
                  Inf : Param_Info renames Infos (I);
                  Nm  : constant String := "L" & Ada.Strings.Fixed.Trim
                          (I'Image, Ada.Strings.Both);
                  CT  : constant String := -Inf.C_Type;
                  Arg : Unbounded_String;
               begin
                  case Inf.Class is
                     when PC_Self =>
                        Arg := +("Copendaq.Types." & CT
                                 & " (Handle (Self))");
                     when PC_In_Bool =>
                        Arg := +("(if " & (-Inf.Ada_Name)
                                 & " then 1 else 0)");
                     when PC_In_Int =>
                        Arg := +("Copendaq.daqInt (" & (-Inf.Ada_Name)
                                 & ")");
                     when PC_In_UInt | PC_In_Err | PC_In_Enum =>
                        Arg := Inf.Ada_Name;
                     when PC_In_Float =>
                        Arg := +("Copendaq.daqFloat (" & (-Inf.Ada_Name)
                                 & ")");
                     when PC_In_Size =>
                        Arg := +("Copendaq.daqSizeT (" & (-Inf.Ada_Name)
                                 & ")");
                     when PC_In_Str =>
                        Arg := +Nm;
                     when PC_In_DaqStr =>
                        Arg := +("Copendaq.Types.daqString (" & Nm & ")");
                     when PC_In_List | PC_In_Dict | PC_In_Event
                        | PC_In_Iface =>
                        Arg := +("Copendaq.Types." & CT & " (Handle ("
                                 & (-Inf.Ada_Name) & "))");
                     when PC_In_Obj =>
                        if CT = "daqBaseObject" then
                           Arg := +("Handle (" & (-Inf.Ada_Name) & ")");
                        else
                           Arg := +Obj_Borrow_Expr (CT, -Inf.Ada_Name);
                        end if;
                     when Out_Class =>
                        Arg := +Nm;
                     when others =>
                        Arg := +Nm;
                  end case;
                  if I > 1 then
                     Append (Body_B, "," & NL & "         ");
                  end if;
                  Append (Body_B, -Arg);
               end;
            end loop;
            Append (Body_B, ");" & NL);

            --  Release temporaries, then check.
            for I in Infos'Range loop
               declare
                  Inf : Param_Info renames Infos (I);
                  Nm  : constant String := "L" & Ada.Strings.Fixed.Trim
                          (I'Image, Ada.Strings.Both);
               begin
                  if Inf.Class = PC_In_Str then
                     Append (Body_B, "      Interfaces.C.Strings.Free ("
                             & Nm & ");" & NL);
                  elsif Inf.Class = PC_In_DaqStr then
                     Append (Body_B, "      Release_Handle (" & Nm & ");"
                             & NL);
                  end if;
               end;
            end loop;
            Append (Body_B, "      Check (Code, """ & C_Name & """);" & NL);

            --  Convert out params / build result.
            for I in Infos'Range loop
               declare
                  Inf : Param_Info renames Infos (I);
                  Nm  : constant String := "L" & Ada.Strings.Fixed.Trim
                          (I'Image, Ada.Strings.Both);
                  Is_Result : constant Boolean := I = Result_Idx;

                  function Converted return String is
                  begin
                     case Inf.Class is
                        when PC_Out_Bool =>
                           return Nm & " /= 0";
                        when PC_Out_Int =>
                           return "Long_Long_Integer (" & Nm & ")";
                        when PC_Out_UInt | PC_Out_Enum =>
                           return Nm;
                        when PC_Out_Float =>
                           return "Long_Float (" & Nm & ")";
                        when PC_Out_Size =>
                           return "Natural (" & Nm & ")";
                        when PC_Out_CStr =>
                           return "Interfaces.C.Strings.Value (" & Nm & ")";
                        when PC_Out_DaqStr =>
                           return "From_Daq_String_Handle "
                             & "(Copendaq.daqBaseObject (" & Nm & "))";
                        when PC_Out_List =>
                           return "Daq.Lists.Take "
                             & "(Copendaq.daqBaseObject (" & Nm & "))";
                        when PC_Out_Dict =>
                           return "Daq.Dicts.Take "
                             & "(Copendaq.daqBaseObject (" & Nm & "))";
                        when PC_Out_Event =>
                           return "Daq.Events.Take "
                             & "(Copendaq.daqBaseObject (" & Nm & "))";
                        when PC_Out_Obj =>
                           if -Inf.C_Type = "daqBaseObject" then
                              return "Daq.Take (" & Nm & ")";
                           else
                              return "Daq.Take (Copendaq.daqBaseObject ("
                                & Nm & "))";
                           end if;
                        when PC_Out_Iface =>
                           if Is_Result then
                              --  Qualified expression: picks the result
                              --  type's own inherited Take unambiguously,
                              --  then implicitly converts to 'Class.
                              return Type_Name (-Inf.Iface)
                                & "'(Take (Copendaq.daqBaseObject ("
                                & Nm & ")))";
                           else
                              return "Daq.Take (Copendaq.daqBaseObject ("
                                & Nm & "))";
                           end if;
                        when others =>
                           return Nm;
                     end case;
                  end Converted;
               begin
                  if Inf.Class in Out_Class then
                     if Is_Result then
                        Append (Body_B, "      return " & Converted & ";"
                                & NL);
                     else
                        Append (Body_B, "      " & (-Inf.Ada_Name)
                                & " := " & Converted & ";" & NL);
                     end if;
                  end if;
               end;
            end loop;
            if Result_Idx = 0 then
               null;  --  plain procedure
            end if;
            Append (Body_B, "   end " & Ada_Name & ";" & NL & NL);
         end;
      end Emit_Subprogram;

      ----------------------------------------------------------------
      --  Interface walk
      ----------------------------------------------------------------

      procedure Emit_Interface (Non_Iface : String) is
         C_Type   : constant String := "daq" & Non_Iface;
         Ada_T    : constant String := Type_Name (Non_Iface);
         Prefix   : constant String := C_Type & "_";
         Has_Id_Getter : constant Boolean :=
           Proc_Index.Contains (Prefix & "getInterfaceId")
           and then Have_Symbol (Prefix & "getInterfaceId");
         Parent : Unbounded_String := +"Daq.Object";

         Used : String_Sets.Set;  --  Ada subprogram names in this section
      begin
         if Base_Of.Contains (Non_Iface) then
            declare
               B : constant String := Base_Of.Element (Non_Iface);
            begin
               if Gen_Set.Contains (B) then
                  Parent := +Type_Name (B);
               end if;
            end;
         end if;

         Append (Spec_B, NL & "   --  I" & Non_Iface & " (" & C_Type & ")"
                 & NL);
         Append (Spec_B, "   type " & Ada_T & " is new " & (-Parent)
                 & " with null record;" & NL);

         Append (Body_B, NL & "   --  I" & Non_Iface & NL & NL);

         --  Casts
         if Has_Id_Getter then
            declare
               Pkg : constant String :=
                 Config.Package_For_Group
                   (-DB.Procs
                      (Proc_Index.Element (Prefix & "getInterfaceId")).Group);
               Getter : constant String :=
                 "Copendaq." & Pkg & "." & Prefix & "getInterfaceId'Access";
            begin
               Append (Spec_B, "   function As_" & Ada_T
                       & " (From : Daq.Object'Class) return " & Ada_T
                       & "'Class;" & NL);
               Append (Spec_B, "   function Is_" & Ada_T
                       & " (From : Daq.Object'Class) return Boolean;" & NL);
               Append (Body_B,
                 "   function As_" & Ada_T
                 & " (From : Daq.Object'Class) return " & Ada_T
                 & "'Class is" & NL
                 & "   begin" & NL
                 & "      return " & Ada_T & "'(Take (Query_Handle (From,"
                 & NL
                 & "        " & Getter & ", ""I" & Non_Iface & """)));" & NL
                 & "   end As_" & Ada_T & ";" & NL & NL);
               Append (Body_B,
                 "   function Is_" & Ada_T
                 & " (From : Daq.Object'Class) return Boolean is" & NL
                 & "   begin" & NL
                 & "      return Supports (From, " & Getter & ");" & NL
                 & "   end Is_" & Ada_T & ";" & NL & NL);
            end;
         end if;

         --  Methods & factories: all C procs with this exact prefix.
         for P of DB.Procs loop
            declare
               C_Name : constant String := -P.Name;
            begin
               if C_Name'Length > Prefix'Length
                 and then C_Name
                   (C_Name'First .. C_Name'First + Prefix'Length - 1)
                   = Prefix
               then
                  declare
                     M : constant String :=
                       C_Name (C_Name'First + Prefix'Length .. C_Name'Last);
                     Is_Factory : constant Boolean :=
                       M'Length > 6
                       and then M (M'First .. M'First + 5) = "create";
                  begin
                     if M = "getInterfaceId" then
                        null;
                     else
                        declare
                           Base_Name : constant String :=
                             Names.To_Ada_Case (M);
                           Ada_Name : constant String :=
                             (if Type_Names.Contains
                                (Ada.Characters.Handling.To_Lower
                                   (Base_Name))
                              then Base_Name & "_Op"
                              else Base_Name);
                        begin
                           --  Same-section duplicate names are fine
                           --  (overloads); we only avoid type collisions.
                           Used.Include (Ada_Name);
                           Emit_Subprogram
                             (P,
                              Self_Iface =>
                                (if Is_Factory then "" else Non_Iface),
                              Ada_Name => Ada_Name);
                        end;
                     end if;
                  end;
               end if;
            end;
         end loop;
      end Emit_Interface;

      Ordered : String_Vectors.Vector;  --  topological (parents first)

      procedure Order_Interfaces is
         Placed : String_Sets.Set;

         procedure Place (Name : String) is
         begin
            if Placed.Contains (Name) or else not Gen_Set.Contains (Name)
            then
               return;
            end if;
            if Base_Of.Contains (Name) then
               declare
                  B : constant String := Base_Of.Element (Name);
               begin
                  if Gen_Set.Contains (B) and then B /= Name then
                     Place (B);
                  end if;
               end;
            end if;
            Placed.Include (Name);
            Ordered.Append (Name);
         end Place;
      begin
         for I of Model loop
            Place (-I.Name);
         end loop;
      end Order_Interfaces;

   begin
      Load_Symbols;
      RTGen_Model.Load (-Opts.Model_Dir, Model, Opts.Verbose);

      --  Index procs and interface-id constants by name.
      declare
         Idx : Positive := 1;
      begin
         for P of DB.Procs loop
            Proc_Index.Include (-P.Name, Idx);
            Idx := Idx + 1;
         end loop;
         for N of DB.Intf_Ids loop
            Intf_Id_Set.Include (N);
         end loop;
      end;

      --  Decide the generated set.
      for I of Model loop
         declare
            N : constant String := -I.Name;
         begin
            if I.Base /= Null_Unbounded_String then
               Base_Of.Include (N, -I.Base);
            end if;
            if Is_Hand_Interface (N) then
               null;
            elsif not DB.Known_Opaque.Contains ("daq" & N)
              and then not Proc_Index.Contains
                             ("daq" & N & "_getInterfaceId")
            then
               --  Method-less interfaces (e.g. IChannel) get no opaque
               --  typedef from RTGen's C generator, only the interface id;
               --  they are still generated (type + casts, methods inherited)
               --  as long as the id getter exists.
               Skipped.Append ("interface I" & N & " (no C opaque type)");
            else
               Gen_Set.Include (N);
               declare
                  T : constant String := Type_Name (N);
                  L : constant String :=
                    Ada.Characters.Handling.To_Lower (T);
               begin
                  if Type_Names.Contains (L) then
                     raise Program_Error with
                       "type name collision: " & T;
                  end if;
                  Type_Names.Include (L);
               end;
            end if;
         end;
      end loop;

      Order_Interfaces;

      --  Spec prologue
      Append (Spec_B, "pragma Warnings (Off);" & NL);
      Append (Spec_B, "with System;" & NL);
      Append (Spec_B, "with Copendaq;" & NL);
      Append (Spec_B, "with Copendaq.Types;" & NL);
      Append (Spec_B, "with Daq.Dicts;" & NL);
      Append (Spec_B, "with Daq.Events;" & NL);
      Append (Spec_B, "with Daq.Lists;" & NL & NL);
      Append (Spec_B, Banner);
      Append (Spec_B,
        "--  Generated wrappers for the full openDAQ SDK surface." & NL
        & "--  Every operation takes Self : <T>'Class as first parameter" & NL
        & "--  (prefix-callable: Obj.Get_Name), raises Opendaq_Error on" & NL
        & "--  failed error codes, and returns owned wrappers (RAII)." & NL);
      Append (Spec_B, "package Daq.API is" & NL & NL);
      Append (Spec_B, "   --  Forward declarations" & NL);
      for N of Ordered loop
         Append (Spec_B, "   type " & Type_Name (N) & " is tagged;" & NL);
      end loop;

      --  Body prologue
      Append (Body_B, "pragma Warnings (Off);" & NL);
      Append (Body_B, "with Interfaces.C.Strings;" & NL);
      Append (Body_B, "with System;" & NL);
      Append (Body_B, "with Copendaq;" & NL);
      Append (Body_B, "with Copendaq.Intf_IDs;" & NL);
      Append (Body_B, "with Copendaq.Types;" & NL);
      for I in 1 .. Config.Group_Count loop
         Append (Body_B, "with Copendaq."
                 & Config.Package_For_Group (Config.Group_Dir (I)) & ";"
                 & NL);
      end loop;
      Append (Body_B, NL & Banner);
      Append (Body_B, "package body Daq.API is" & NL & NL);
      Append (Body_B, "   use type Copendaq.daqBool;" & NL);

      for N of Ordered loop
         Emit_Interface (N);
      end loop;

      Append (Spec_B, NL & "end Daq.API;" & NL);
      Append (Body_B, NL & "end Daq.API;" & NL);

      Output.Emit (W, -Opts.High_Out & "/daq-api.ads", -Spec_B);
      Output.Emit (W, -Opts.High_Out & "/daq-api.adb", -Body_B);
      Output.Sweep (W, -Opts.High_Out);
      Output.Report (W, "gen-high");

      Put_Line ("gen-high:" & Ordered.Length'Image & " interfaces");
      if not Skipped.Is_Empty then
         Put_Line ("gen-high: skipped" & Skipped.Length'Image & ":");
         for S of Skipped loop
            Put_Line ("  " & S);
         end loop;
      end if;
   end Run;

end Codegen.Emit_High;
