with Ada.Characters.Handling;
with Ada.Text_IO;
with Interfaces;

with Codegen.Config;

package body Codegen.Emit_Low is

   use C_Model;
   use type Interfaces.Unsigned_32;

   NL : constant Character := ASCII.LF;

   Banner : constant String :=
     "--  GENERATED by tools/opendaq_codegen - DO NOT EDIT."
     & NL
     & "--  Regenerate with: ./daq gen"
     & NL;

   function Hex (V : Interfaces.Unsigned_32) return String is
      Digits_S : constant String := "0123456789ABCDEF";
      R : String (1 .. 8);
      X : Interfaces.Unsigned_32 := V;
   begin
      for I in reverse R'Range loop
         R (I) := Digits_S (Natural (X and 16#F#) + 1);
         X := Interfaces.Shift_Right (X, 4);
      end loop;
      return "16#" & R (1 .. 4) & "_" & R (5 .. 8) & "#";
   end Hex;

   --  Ada text for one parameter: "name : [mode ]type". Returns "" when the
   --  parameter cannot be mapped (caller records the proc as unmappable).
   function Param_Text (DB : Database; P : Param) return String is
      use Codegen.Config;
      T    : constant String := -P.C_Type;
      Kind : constant Prelude_Kind := Prelude_Kind_Of (T);
      Name : constant String := -P.Name;

      function Mk (Mode, Ada_Type : String) return String is
        (Name & " : " & Mode & Ada_Type);
   begin
      case Kind is
         when Handle =>
            --  C daqBaseObject* == Ada handle value (Address-derived)
            case P.Ptr is
               when 1 => return Mk ("", "daqBaseObject");
               when 2 => return Mk ("out ", "daqBaseObject");
               when others => return "";
            end case;
         when Scalar | Enum_Type =>
            case P.Ptr is
               when 0 => return Mk ("", T);
               when 1 => return Mk ("in out ", T);
               when others => return "";
            end case;
         when Pointer_Alias | Callback =>
            case P.Ptr is
               when 0 => return Mk ("", T);
               when 1 => return Mk ("in out ", T);
               when others => return "";
            end case;
         when Record_Type =>
            case P.Ptr is
               when 0 => return Mk ("", T);
               when 1 => return Mk ("in out ", T);
               when others => return "";
            end case;
         when Not_Prelude =>
            if DB.Known_Opaque.Contains (T) then
               case P.Ptr is
                  when 1 => return Mk ("", "Copendaq.Types." & T);
                  when 2 => return Mk ("out ", "Copendaq.Types." & T);
                  when others => return "";
               end case;
            elsif DB.Known_Enums.Contains (T) then
               case P.Ptr is
                  when 0 => return Mk ("", "Copendaq.Types." & T);
                  when 1 => return Mk ("in out ", "Copendaq.Types." & T);
                  when others => return "";
               end case;
            elsif T = "void" then
               case P.Ptr is
                  when 1 => return Mk ("", "daqVoidPtr");
                  when 2 => return Mk ("in out ", "daqVoidPtr");
                  when others => return "";
               end case;
            elsif T = "char" then
               case P.Ptr is
                  when 1 => return Mk ("", "daqCharPtr");
                  when 2 => return Mk ("in out ", "daqCharPtr");
                  when others => return "";
               end case;
            else
               declare
                  M : constant String := Map_C_Base (T);
               begin
                  if M = "" then
                     return "";
                  end if;
                  case P.Ptr is
                     when 0 => return Mk ("", M);
                     when 1 => return Mk ("in out ", M);
                     when others => return "";
                  end case;
               end;
            end if;
      end case;
   end Param_Text;

   --  Ada return type ("" = procedure; "?" = unmappable).
   function Ret_Text (DB : Database; Ret : String) return String is
      use Codegen.Config;
   begin
      if Ret = "" then
         return "";
      elsif Prelude_Kind_Of (Ret) in Scalar | Enum_Type | Pointer_Alias then
         return Ret;
      elsif DB.Known_Enums.Contains (Ret) then
         return "Copendaq.Types." & Ret;
      else
         declare
            M : constant String := Map_C_Base (Ret);
         begin
            if M = "" then
               return "?";
            end if;
            return M;
         end;
      end if;
   end Ret_Text;

   procedure Run
     (DB      : C_Model.Database;
      Out_Dir : String;
      W       : in out Output.Writer)
   is
      Lower_Seen : String_Sets.Set;  --  case-insensitive collision guard
      Skipped    : String_Vectors.Vector;

      procedure Check_Collision (Name : String) is
         L : constant String := Ada.Characters.Handling.To_Lower (Name);
      begin
         if Lower_Seen.Contains (L) then
            raise Program_Error with
              "case-insensitive name collision: " & Name;
         end if;
         Lower_Seen.Include (L);
      end Check_Collision;

      ----------------------------------------------------------------
      --  Copendaq.Types
      ----------------------------------------------------------------

      function Render_Types return String is
         B : Unbounded_String;
      begin
         Append (B, "pragma Warnings (Off);" & NL);
         Append (B, "with Interfaces.C;" & NL & NL);
         Append (B, Banner);
         Append (B, "--  All opaque interface handles and enumerations of the"
                 & NL);
         Append (B, "--  copendaq C API. Handles are typed addresses: the Ada"
                 & NL);
         Append (B, "--  value corresponds to the C interface POINTER."
                 & NL);
         Append (B, "package Copendaq.Types is" & NL & NL);

         Append (B, "   --  Opaque interface handles" & NL & NL);
         for Name of DB.Opaques loop
            Check_Collision (Name);
            Append (B, "   type " & Name & " is new daqBaseObject;" & NL);
         end loop;

         Append (B, NL & "   --  Enumerations" & NL);
         for E of DB.Enums loop
            declare
               Name : constant String := -E.Name;
               Fits : Boolean := E.Enumerable and E.Resolved;
            begin
               if not E.Resolved then
                  Skipped.Append ("enum " & Name & " (unresolved values)");
               else
                  Check_Collision (Name);
                  for M of E.Members loop
                     if M.Value > 16#7FFF_FFFF# then
                        Fits := False;
                     end if;
                  end loop;
                  Append (B, NL);
                  if Fits then
                     Append (B, "   type " & Name & " is" & NL);
                     declare
                        First : Boolean := True;
                     begin
                        for M of E.Members loop
                           Check_Collision (-M.Name);
                           if First then
                              Append (B, "     (");
                           else
                              Append (B, "," & NL & "      ");
                           end if;
                           Append (B, -M.Name);
                           First := False;
                        end loop;
                     end;
                     Append (B, ");" & NL);
                     Append (B, "   for " & Name & " use" & NL);
                     declare
                        First : Boolean := True;
                     begin
                        for M of E.Members loop
                           if First then
                              Append (B, "     (");
                           else
                              Append (B, "," & NL & "      ");
                           end if;
                           Append (B, -M.Name & " =>" & M.Value'Image);
                           First := False;
                        end loop;
                     end;
                     Append (B, ");" & NL);
                     Append (B, "   for " & Name & "'Size use 32;" & NL);
                     Append (B, "   pragma Convention (C, " & Name & ");"
                             & NL);
                  else
                     --  Duplicate/huge values: integer type + constants.
                     Append (B, "   type " & Name
                             & " is new Interfaces.C.unsigned;" & NL);
                     for M of E.Members loop
                        Check_Collision (-M.Name);
                        Append (B, "   " & (-M.Name) & " : constant "
                                & Name & " := " & Hex (M.Value) & ";" & NL);
                     end loop;
                  end if;
               end if;
            end;
         end loop;

         Append (B, NL & "end Copendaq.Types;" & NL);
         return -B;
      end Render_Types;

      ----------------------------------------------------------------
      --  Copendaq.Errors
      ----------------------------------------------------------------

      function Render_Errors return String is
         B : Unbounded_String;
      begin
         Append (B, Banner);
         Append (B, "--  DAQ_* error / status constants (DAQ_ERROR_CODE"
                 & " macros evaluated)." & NL);
         Append (B, "package Copendaq.Errors is" & NL & NL);
         for C of DB.Consts loop
            Append (B, "   " & (-C.Name) & " : constant daqErrCode := "
                    & Hex (C.Value) & ";" & NL);
         end loop;
         Append (B, NL & "end Copendaq.Errors;" & NL);
         return -B;
      end Render_Errors;

      ----------------------------------------------------------------
      --  Copendaq.Intf_IDs
      ----------------------------------------------------------------

      function Render_Intf_IDs return String is
         B : Unbounded_String;
      begin
         Append (B, Banner);
         Append (B, "--  Interface-id DATA imports. Quarantined here: on"
                 & " Windows, data imports" & NL);
         Append (B, "--  need auto-import pseudo-relocations; prefer the"
                 & " daqX_getInterfaceId" & NL);
         Append (B, "--  functions (the high-level layer uses only those)."
                 & NL);
         Append (B, "package Copendaq.Intf_IDs is" & NL & NL);
         for Name of DB.Intf_Ids loop
            Append (B, "   " & Name & " : constant daqIntfID" & NL);
            Append (B, "     with Import => True, Convention => C,"
                    & " External_Name => """ & Name & """;" & NL & NL);
         end loop;
         Append (B, "end Copendaq.Intf_IDs;" & NL);
         return -B;
      end Render_Intf_IDs;

      ----------------------------------------------------------------
      --  Function packages
      ----------------------------------------------------------------

      function Render_Group (Dir : String; Pkg : String) return String is
         B : Unbounded_String;
      begin
         Append (B, "pragma Warnings (Off);" & NL);
         Append (B, "with Interfaces.C;" & NL);
         Append (B, "with Copendaq.Types;" & NL & NL);
         Append (B, Banner);
         Append (B, "--  Imported subprograms for the """ & Dir
                 & """ headers." & NL);
         Append (B, "package Copendaq." & Pkg & " is" & NL & NL);

         for P of DB.Procs loop
            if -P.Group = Dir then
               declare
                  Name    : constant String := -P.Name;
                  Ret     : constant String := Ret_Text (DB, -P.Ret);
                  Broken  : Boolean := Ret = "?";
                  Profile : Unbounded_String;
               begin
                  Check_Collision (Name);
                  if not P.Params.Is_Empty then
                     declare
                        First : Boolean := True;
                     begin
                        Append (Profile, NL & "     (");
                        for Prm of P.Params loop
                           declare
                              PT : constant String := Param_Text (DB, Prm);
                           begin
                              if PT = "" then
                                 Broken := True;
                              end if;
                              if not First then
                                 Append (Profile, ";" & NL & "      ");
                              end if;
                              Append (Profile, PT);
                              First := False;
                           end;
                        end loop;
                        Append (Profile, ")");
                     end;
                  end if;

                  if Broken then
                     Skipped.Append
                       ("proc " & Name & " (unmappable profile)");
                  else
                     if Ret = "" then
                        Append (B, "   procedure " & Name);
                        Append (B, Profile);
                     else
                        Append (B, "   function " & Name);
                        Append (B, Profile);
                        Append (B, " return " & Ret);
                     end if;
                     Append (B, NL
                             & "     with Import => True, Convention => C,"
                             & NL
                             & "          External_Name => """ & Name
                             & """;" & NL & NL);
                  end if;
               end;
            end if;
         end loop;

         Append (B, "end Copendaq." & Pkg & ";" & NL);
         return -B;
      end Render_Group;

      function File_Name (Unit : String) return String is
         L : String := Ada.Characters.Handling.To_Lower (Unit);
      begin
         for I in L'Range loop
            if L (I) = '.' then
               L (I) := '-';
            end if;
         end loop;
         return Out_Dir & "/" & L & ".ads";
      end File_Name;

   begin
      Output.Emit (W, File_Name ("Copendaq.Types"), Render_Types);
      Output.Emit (W, File_Name ("Copendaq.Errors"), Render_Errors);
      Output.Emit (W, File_Name ("Copendaq.Intf_IDs"), Render_Intf_IDs);
      for I in 1 .. Config.Group_Count loop
         declare
            Dir : constant String := Config.Group_Dir (I);
            Pkg : constant String := Config.Package_For_Group (Dir);
         begin
            Output.Emit (W, File_Name ("Copendaq." & Pkg),
                         Render_Group (Dir, Pkg));
         end;
      end loop;
      Output.Sweep (W, Out_Dir);

      if not Skipped.Is_Empty then
         Ada.Text_IO.Put_Line ("emit_low: skipped declarations:");
         for S of Skipped loop
            Ada.Text_IO.Put_Line ("  " & S);
         end loop;
      end if;
      if not DB.Unmapped.Is_Empty then
         Ada.Text_IO.Put_Line ("emit_low: WARNING unmapped base types:");
         for T of DB.Unmapped loop
            Ada.Text_IO.Put_Line ("  " & T);
         end loop;
      end if;
   end Run;

end Codegen.Emit_Low;
